### ISSUE TITLE
Is this editor suitble for the EP7 server/clients ?

### ISSUE THREAD

**Issue by zhlown** [osiy1996/archlord#3]
hi Osiy, I tried to use your editor tools to edit the file of ALReborn EP7, but it crashed.
If I want to use this editor on my own server, is there any conditions should be meet ?
Or this tool just cannot work on other server/clients ?

**Comment by osiy1996** [comment]
It depends on what you are trying to edit.

Object files and most binary files share the same formats, but some INI files are different.

You can either mix and match, adjust your version of file formats, or make changes at the source code level so that it is compatible with your version of INI files.

To be honest, I did put a lot of effort into terrain/object editors so I would be happy to see someone do something with it.

![image](https://github.com/osiy1996/archlord/assets/140885303/4e2cf20a-ae01-40a9-a95b-6a6f7cbfad1e)

**Comment by zhlown** [comment]
Understand. 
These functions are pretty cool, thank you for share.
